### ISSUE TITLE
javascript packages

### ISSUE THREAD

**Issue by jolyonb** [mitodl/mitx-grading-library#207]
Because so many javascript packages are being loaded to run our tests, there's a constant barrage of security alerts associated with this project. Any chance we can simplify the package list to minimize this?

**Comment by ChristopherChudzicki** [comment]
**Short answer**: We can probably just delete `package-lock.json`. Usually it’s recommended to commit `package-lock` into source control, but I think in our case it is OK not to. 

For JS projects, there are two dependency listings:
- `package.json` lists direct dependencies (among other things)
- `package-lock.json` Lists all nested dependencies

Usually, `package-lock` is used for the actual installation. From https://stackoverflow.com/questions/52499617/what-is-the-difference-between-npm-install-and-npm-ci :
>npm install reads package.json to create a list of dependencies and uses package-lock.json to inform which versions of these dependencies to install. If a dependency is not in package-lock.json it will be added by npm install.
>
>npm ci (named after Continuous Integration) installs dependencies directly from package-lock.json and uses package.json only to validate that there are no mismatched versions. If any dependencies are missing or have incompatible versions, it will throw an error.

The usual recommendation is to commit `package-lock.json` into source control to ensure 100% reproducibility of build process. But since we’re only using the packages for testing and not for distribution, there is no danger. 

I find the whole package-lock thing kind of annoying...

**Comment by jolyonb** [comment]
Ok. I'll leave you to figure out how this should work as the resident javascript expert =P
