### ISSUE TITLE
Function application post computation

### ISSUE THREAD

**Issue by jolyonb** [mitodl/mitx-grading-library#30]
We should add an option to the math grader to apply a function to the result post-testing. By supplying a math function, we could do something like take the sin/cosine of the result, so that the answers are invariant up to phases of 2 pi. By supplying a python function, we could do something like have a python function that tests if the entered number satisfies some condition that can be tested programmatically. This could be the first step in allowing a python function that tests if an entered vector is perpendicular to another vector.

**Comment by ChristopherChudzicki** [comment]
I like this, I think it will be useful to physics, and I am sure it would have been useful to Jen in the past.

**Suggested Implementation**: Provide a `comparer` key, which would be a function with signature `comparer(evaluated_input, compare_to, tolerance)`. Example:

```python
# Question: Enter an angle coterminal with pi/3

def comparer(evaluated_input, compare_to, tolerance):
  reduced = evaluated_input - compare_to % 2*math.pi
  return abs(reduced) < tolerance

grader = FormulaGrader(
      answers='pi/3', # evaluated, then passed to comparer as compare_to
      comparer=comparer,
      tolerance=0 # passed to comparer as tolerance
  )
```

This would also be sufficient for more complex examples like testing whether student's input is an eigenvector of a particular matrix. For example:

```python
# Question: Enter an eigenvector of [[4+x, 1], [0, 4]] with eigenvalue 5.
# Answer: Any nonzero multiple of [1, 1-x]

def comparer(evaluated_input, compare_to, tolerance):
  # compare_to is a matrix, and evaluated_input supposedly an eigenvector with eigenvalue 5.
  difference = compare_to*evaluated_input - 5*evaluated_input
  return norm(difference) < tolerance

grader = FormulaGrader(
      answers='[[4+x, 1], [0, 4]]', # evaluated, then passed to comparer as compare_to. The name "answer" is misleading!
      variables=['x'],
      comparer=comparer,
      tolerance=0.1 # passed to comparer as tolerance
  )
```

In the previous example, `answers` did not really play the role of an answer, but was just used so the author could pass the sampled matrix to the comparer function. This is a bit artificial, but works. Might be remedied by making `compare_to` as a keyword alias for `answers`.

**Tolerance**: Both of my example comparer functions would break for percentage tolerances. (In the second case, it's not clear what a tolerance of '1%' would even mean, since the vector could have any length.)  I don't think this is a big problem, but it is a bit annoying in that the default tolerance is `0.01%`.

**Comment by ChristopherChudzicki** [comment]
Yes, I agree with:

>why don't we have a comparer_params key instead, where such things can be specified? We should possibly provide the tolerance function that we use to the comparer also.

I'll work on this tomorrow.

**Comment by jolyonb** [comment]
It seems to me that the answers key may be unnecessary when a comparer is specified. What do you think of changing the answers key to be able to specify a comparison function instead of a string answer? Or possibly, allowing a comparison function, or a string answer _and_ a comparison function (so the comparer can get an evaluated expression from the string). We could build the current comparison function as the default, and allow for an override?

**Comment by ChristopherChudzicki** [comment]
I also foresee no reason to provide all three of `comparer`, `comparer_params`, and `answers`. 

When you say (emphasis mine):

> What do you think of changing the answers key to be able to specify a comparison function instead of a string answer? Or possibly, allowing a comparison function, or _**a string answer and a comparison function**_ (so the comparer can get an evaluated expression from the string).

Do you mean that the single `answers` key could contain the comparer function and the comparer params? I think that would work, we would just have to coerce/standardize string answers like `answers='mc^2'` into 

```python
answers = {
    comparer: within_tolerance,
    comparer_params: ['mc^2']
}
```

I'd have to think a little bit more about how this plays with ItemGrader's looping over answers, but I think it would work naturally.

**Comment by jolyonb** [comment]
Yup, that's basically the idea I had. I think it should go through fairly naturally, although I'd need to refresh my memory on how the list graders are working to be sure.

**Comment by jolyonb** [comment]
Hmm. Do all `comparer_params` get evaluated according to the appropriate variable substitution prior to being submitted to the comparer?

**Comment by ChristopherChudzicki** [comment]
Yes, they need to be. (Hence my original kludge of using `answers`, which are evaluated.) But I think the approach discussed above is nicer and will take only a bit of refactoring.
