### ISSUE TITLE
Check for collisions

### ISSUE THREAD

**Issue by jolyonb** [mitodl/mitx-grading-library#51]
We should check to make sure there are no collisions between user-defined constants and variables (ie, no constant `k` and variable `k`, or worse, defining two constants/variables with the same name). We should also check that user-defined functions don't have duplicated names. We've decided that users should be able to overwrite default constants and functions, however.

**Comment by ChristopherChudzicki** [comment]
We can check for variable--constant collisions and variable--variable collisions. I don't think we can check for constant--constant or function--function collisions without changing how constants and functions are declared because unlike variables, they are declared using dictionaries and Python dictionary literals permit duplicate keys and use the latest:

```python
{
    'a': 5,
    'a': 10
} ==
{
    'a': 10
}
# True
```

Regarding
> We've decided that users should be able to overwrite default constants and functions, however.

Another thing we could do is raise an error (ConfigCollisionError, or something) with a message like "ConfigCollisionError: Declaring variable 'i' will overwrite existing constant 'i'. To proceed anyway, add `suppress_warnings=True` to your grader configuration. Seems like it could be a useful pattern in other cases, too.

**Comment by jolyonb** [comment]
Ah. Good point. Less work for us then! Let's just do variable-variable and variable-constant checks.

I'm happy to greenlight a warning message like that. Let's call it `ConfigCollisionWarning`. Putting in `suppress_warnings=True` will be annoying, but then again, that's kind of the point.

**Comment by ChristopherChudzicki** [comment]
Ok! I'll do it now.

**Comment by ChristopherChudzicki** [comment]
resolved by #53
