### ISSUE TITLE
Refactor abs function to work on vectors

### ISSUE THREAD

**Issue by jolyonb** [mitodl/mitx-grading-library#76]
Another thing that came up in comments and I don't want to lose. I saw that `norm` was added that provides essentially the same functionality, but the `abs` thinking and notation is definitely standard.

**Comment by ChristopherChudzicki** [comment]
By the way: This was intentional on my part, although I suspected you might request a change.

When I teach multivariable calculus and linear algebra, I try very hard to use `norm/length/magnitude` for vectors, and reserve absolute value for scalars. (Incidentally, some error messages use length to refer to number of components. I might change..)

Anyway, I am very happy to change `abs` to work with vectors, but I just want to double check! But I do think we should keep norm as an alias for it.

**Comment by jolyonb** [comment]
Resolved by #88.
